
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Nov 04 19:44:19 CST 2017
//----------------------------------------------------

package edu.utdallas.searchengine;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int OR_SYMBOL = 3;
  public static final int LITERAL = 8;
  public static final int EOF = 0;
  public static final int RIGHT_PAREN = 6;
  public static final int LEFT_PAREN = 5;
  public static final int error = 1;
  public static final int WHITE_SPACE = 7;
  public static final int NOT_SYMBOL = 4;
  public static final int AND_SYMBOL = 2;
}

